-- ════════════════════════════════════════════════════════════════════
-- 🎛️ Migration 06: CRM Roles Extension (V24 — مُبسَّط)
-- ════════════════════════════════════════════════════════════════════
-- 🔧 V24: super_admin/manager/support أُضيفت في 01 مباشرة
--        هذا الملف الآن للأدوار التشغيلية الإضافية فقط (اختياري)
--
-- الأدوار المُعرّفة في 01_foundation:
--   patient, specialist, admin, super_admin, manager, support
--
-- الأدوار الاختيارية لمراحل مستقبلية (تُضاف فقط إذا احتجت):
--   crm_verifier  — للتحقق من مزودي الخدمة
--   crm_lab       — لمشغّلي المختبر
--   crm_dispatcher — للموزّع
--   crm_viewer    — للقراءة فقط (مدققون، شركاء)
-- ════════════════════════════════════════════════════════════════════


-- ════════════════════════════════════════════════════════════════════
-- ⚠️ ملاحظة: لا تُضف هذه الأدوار إلا إذا فعلاً ستستخدمها في الكود
-- ════════════════════════════════════════════════════════════════════
-- ALTER TYPE يعمل على النوع المُعرّف في 01_foundation
-- استخدم ADD VALUE IF NOT EXISTS للأمان

-- أدوار CRM اختيارية (مُعطّلة حالياً - فعّلها عند الحاجة):

-- ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'crm_verifier';
-- ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'crm_lab';
-- ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'crm_dispatcher';
-- ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'crm_viewer';


-- ════════════════════════════════════════════════════════════════════
-- ✅ Migration 06 Complete
-- ════════════════════════════════════════════════════════════════════
--
-- 📋 لإنشاء أول super_admin:
--
-- 1) اذهب إلى Supabase Auth:
--    https://supabase.com/dashboard/project/ioulxemokusfeykjcaxg/auth/users
--    → Add user → Create new user
--    → Email: admin@spirmedical.iq
--    → Password: <كلمة قوية>
--    → ✅ Auto Confirm User
--    → Create
--
-- 2) انسخ UUID المُنشأ من Auth Users
--
-- 3) شغّل هذا الـ SQL في SQL Editor (استبدل PASTE_UUID_HERE):
--
-- INSERT INTO public.users (id, phone, full_name, email, role)
-- VALUES (
--   'PASTE_UUID_HERE',
--   '+9647700000000',
--   'المدير العام',
--   'admin@spirmedical.iq',
--   'super_admin'
-- )
-- ON CONFLICT (id) DO UPDATE SET
--   role = 'super_admin',
--   full_name = EXCLUDED.full_name,
--   email = EXCLUDED.email
-- RETURNING id, email, role;
--
-- 4) سجّل دخول في: https://spirmedical-wep.vercel.app/admin44
-- ════════════════════════════════════════════════════════════════════
